### ISSUE TITLE
Recode app in C# WPF with MahApps metro design.

### ISSUE THREAD

**Issue by Ahmad45123** [Ahmad45123/ExtremeStudio#12]
Work is in the branch `newes`
https://github.com/JohnyMac/ExtremeStudio/tree/newes

Using this library for theming: 
https://github.com/MahApps/MahApps.Metro

**Comment by JohnyMac** [comment]
This thing is taking sone time!!!!!
Sorry for huge delay guys.

Just wanted to say I am still alive haha.

**Comment by Ahmad45123** [comment]
This has been cancelled due to my limited time. I'll continue to support the original application and add features in my free time.
