### ISSUE TITLE
Warning: The manifest for this application does not have a signature. Signature validation will be ignored.

### ISSUE THREAD

**Issue by JohnMagdy** [Ahmad45123/ExtremeStudio#24]
No Comment.

**Comment by Ahmad45123** [comment]
I'm not sure what do you want exactly.

**Comment by JohnMagdy** [comment]
On Downloading/Installing the Application it stopped suddenly and thorwen an Warning with that Message(It seems like ExtremeStudio's manifest.json's Author Signuature isn't Validated...).

**Comment by Ahmad45123** [comment]
Let me know if this will still happen in the new coming feature
