### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by xISRAPILx** [Ahmad45123/ExtremeStudio#42]
I can not compile the project.
![image](https://user-images.githubusercontent.com/28113262/40880516-26a0e8da-66bb-11e8-9edf-9b84fe9fab58.png)

Build properties button:
![image](https://user-images.githubusercontent.com/28113262/40880527-5a268070-66bb-11e8-804f-28528197da23.png)

Instelled plugins icon:
![image](https://user-images.githubusercontent.com/28113262/40880548-ad335928-66bb-11e8-97fd-f99cad23fd02.png)

**Comment by Ahmad45123** [comment]
Can you send me a picture of your server directory ? How did you get to that error ?

**Comment by Ahmad45123** [comment]
Should be fixed now.. Relaunch ExtremeStudio and it'll ask to update.

**Comment by Ahmad45123** [comment]
Should be fixed now.. Relaunch ExtremeStudio and it'll ask to update.

**Comment by xISRAPILx** [comment]
Compilation goes on forever. @Ahmad45123
