### ISSUE TITLE
No support for legacy includes

### ISSUE THREAD

**Issue by Ahmad45123** [Ahmad45123/ExtremeStudio#45]

**Comment by Ahmad45123** [comment]
@xISRAPILx is this fixed now ??
You leave your includes in pawno/include

**Comment by xISRAPILx** [comment]
@Ahmad45123 One moment

**Comment by xISRAPILx** [comment]
@Ahmad45123 https://imgur.com/a/hetIPmq
It asks for something that is already there. A strange mistake. -_-

**Comment by Ahmad45123** [comment]
You can't have the include in both your pawno folder and downloaded as a dependency.
For example, if you downloaded Pawn.Cmd from the package system, then please delete it from your pawno/include folder. Same thing for streamer and all the rest.

**Comment by xISRAPILx** [comment]
It's decided. I re-created the project.
