### ISSUE TITLE
Unhandled exeption while loading a recent project

### ISSUE THREAD

**Issue by AkinoKiritani** [Ahmad45123/ExtremeStudio#49]
Hi,
I just wanted to look into the editor and found accidentally this bug/crash

![grafik](https://user-images.githubusercontent.com/3106267/56816034-ff305a80-6842-11e9-8b83-ff85941809fb.png)

It happend after creating create a project, close it without doing anything and try to open it again over the "Recent" tab from the Projectbrowser.

[Crashreport](https://github.com/Ahmad45123/ExtremeStudio/files/3121777/crash.txt)

**Comment by Reclusior** [comment]
after testing a little while, the problem comes up every time you close a project with the "Close Project Button", so the Program will load the Projectbrowser (again)

**Comment by Ahmad45123** [comment]
Fixed.
