### ISSUE TITLE
bug Invalid parent form.

### ISSUE THREAD

**Issue by Jumpix** [Ahmad45123/ExtremeStudio#61]
![image](https://user-images.githubusercontent.com/23275512/58266743-f754cf00-7d8a-11e9-8c94-cd4895b9fc38.png)
Don`t opening the gamemode .pwn file. gamemode created in Extreme Studio

**Comment by Ahmad45123** [comment]
Bug fixed in new update.

**Comment by Ahmad45123** [comment]
Please uninstall the old version before installing the new one as the update mechanism for some reason seems to be broken.
